// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwpiqq9lEtQiLFF8-v3hw5YW5l6Cej42E',
    appId: '1:1002246417950:web:67371bc6f6db30eb21480f',
    messagingSenderId: '1002246417950',
    projectId: 'taskly-app-dbf81',
    authDomain: 'taskly-app-dbf81.firebaseapp.com',
    storageBucket: 'taskly-app-dbf81.firebasestorage.app',
    measurementId: 'G-TSLCFDEE9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_wtQFbBQjGq0mjC6ogIRsm-xfVi_JoBk',
    appId: '1:1002246417950:android:1c279b9543833cc521480f',
    messagingSenderId: '1002246417950',
    projectId: 'taskly-app-dbf81',
    storageBucket: 'taskly-app-dbf81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArFNiX64cHbiA5wfQuJEUF182rjR63jHs',
    appId: '1:1002246417950:ios:b533556380e1755b21480f',
    messagingSenderId: '1002246417950',
    projectId: 'taskly-app-dbf81',
    storageBucket: 'taskly-app-dbf81.firebasestorage.app',
    iosBundleId: 'com.example.tasklyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArFNiX64cHbiA5wfQuJEUF182rjR63jHs',
    appId: '1:1002246417950:ios:b533556380e1755b21480f',
    messagingSenderId: '1002246417950',
    projectId: 'taskly-app-dbf81',
    storageBucket: 'taskly-app-dbf81.firebasestorage.app',
    iosBundleId: 'com.example.tasklyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwpiqq9lEtQiLFF8-v3hw5YW5l6Cej42E',
    appId: '1:1002246417950:web:3fe41327b5545fb421480f',
    messagingSenderId: '1002246417950',
    projectId: 'taskly-app-dbf81',
    authDomain: 'taskly-app-dbf81.firebaseapp.com',
    storageBucket: 'taskly-app-dbf81.firebasestorage.app',
    measurementId: 'G-MTFMKE7ML5',
  );
}
